openapi: 3.0.1
info:
  title: edwareidentity
  description: API Definition of edwareidentity
  version: 1.0.0
servers:
- url: http://localhost:8290/sagecrmapi_edwareidentity
paths:
  /:
    get:
      responses:
        default:
          description: Default response
